# Build diagnostics
bnc = {$detail}
    .title = Invalid bnc invocation
    .code = BNC
    .label = invalid command-line argument
bnc-engine = {$detail}
    .title = Basic Next engine could not be started
    .code = BNC_ENGINE
    .label = engine launch failed
target-unsupported-entrypoint = Target {$target} does not support this entrypoint: {$detail}
    .title = Unsupported entrypoint
    .code = TARGET_UNSUPPORTED_ENTRYPOINT
    .label = unsupported entrypoint
target-unsupported-host = Target {$target} does not provide this HOST capability: {$detail}
    .title = Unsupported HOST capability
    .code = TARGET_UNSUPPORTED_HOST
    .label = unsupported capability
target-unsupported-op = Target {$target} does not support this operation: {$detail}
    .title = Unsupported operation for target
    .code = TARGET_UNSUPPORTED_OP
    .label = unsupported operation
target-unsupported-type = Target {$target} does not support this type: {$detail}
    .title = Unsupported type for target
    .code = TARGET_UNSUPPORTED_TYPE
    .label = unsupported type
target-unsupported-llvm = LLVM target {$target} rejected this operation: {$detail}
    .title = Unsupported LLVM operation
    .code = TARGET_UNSUPPORTED_LLVM
    .label = unsupported operation
