# Build diagnostics
bnc = {$detail}
    .title = Invalid bnc invocation
    .code = BNC
    .label = invalid command-line argument
    .cause = the command line does not match bnc's options
    .help = run `bnc --help` for the accepted options
bnc-engine = {$detail}
    .title = Basic Next engine could not be started
    .code = BNC_ENGINE
    .label = engine launch failed
    .cause = bnc could not start the frontend or the code generator
    .help = check the installation, then retry with --verbose
target-unsupported-entrypoint = Target {$target} does not support this entrypoint: {$detail}
    .title = Unsupported entrypoint
    .code = TARGET_UNSUPPORTED_ENTRYPOINT
    .label = unsupported entrypoint
    .cause = the target cannot start a program with this entry point
    .help = declare FUNCTION Start() AS INTEGER or AS VOID, or build for the native target
target-unsupported-host = Target {$target} does not provide this HOST capability: {$detail}
    .title = Unsupported HOST capability
    .code = TARGET_UNSUPPORTED_HOST
    .label = unsupported capability
    .cause = the target provides no implementation of this HOST capability
    .help = build for a target that provides it, or run the program with `bni run`
target-unsupported-op = Target {$target} does not support this operation: {$detail}
    .title = Unsupported operation for target
    .code = TARGET_UNSUPPORTED_OP
    .label = unsupported operation
    .cause = the compiler supports this construct only on other targets (docs/architecture/support-matrix.md)
    .help = run the program with `bni run`, or build for the native target
target-unsupported-type = Target {$target} does not support this type: {$detail}
    .title = Unsupported type for target
    .code = TARGET_UNSUPPORTED_TYPE
    .label = unsupported type
    .cause = the compiler cannot represent this type on the target
    .help = run the program with `bni run`, or use a type the target supports
target-unsupported-llvm = LLVM target {$target} rejected this operation: {$detail}
    .title = Unsupported LLVM operation
    .code = TARGET_UNSUPPORTED_LLVM
    .label = unsupported operation
    .cause = the LLVM backend rejected an operation it was asked to emit
    .help = this is a bnc defect: report it with the program; `bni run` executes it meanwhile
