# Runtime and IR diagnostics
invalid-ir = Invalid intermediate representation: {$detail}
    .title = Invalid intermediate representation
    .code = INVALID_IR
    .label = invalid IR
ir-lowering = IR lowering failed: {$detail}
    .title = IR lowering failed
    .code = IR_LOWERING
    .label = unsupported lowering
IMPORT_CYCLE = Import cycle includes {$detail}.
    .title = Import cycle
    .code = IMPORT_CYCLE
    .label = cycle edge
MODULE_LIMIT = Module graph limit exceeded: {$detail}.
    .title = Module graph limit exceeded
    .code = MODULE_LIMIT
    .label = module graph
ALLOCATION_SIZE_INVALID = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = ALLOCATION_SIZE_INVALID
    .label = diagnostic
ALLOCATION_SIZE_OVERFLOW = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = ALLOCATION_SIZE_OVERFLOW
    .label = diagnostic
ALLOCATION_TOO_LARGE = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = ALLOCATION_TOO_LARGE
    .label = diagnostic
BUILD_EMISSION_FAILED = {$message}
    .title = Runtime or toolchain diagnostic
    .code = BUILD_EMISSION_FAILED
    .label = diagnostic
BUILD_TOOLCHAIN_UNAVAILABLE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = BUILD_TOOLCHAIN_UNAVAILABLE
    .label = diagnostic
CONFIG_INVALID = {$message}
    .title = Runtime or toolchain diagnostic
    .code = CONFIG_INVALID
    .label = diagnostic
DEBUG_TERMINATED = {$message}
    .title = Runtime or toolchain diagnostic
    .code = DEBUG_TERMINATED
    .label = diagnostic
DISPATCH = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = DISPATCH
    .label = diagnostic
DIVISION_BY_ZERO = {$operation} cannot use zero as its divisor.
    .title = Runtime or toolchain diagnostic
    .code = DIVISION_BY_ZERO
    .label = diagnostic
    .cause = the right-hand operand evaluated to zero
    .help = provide a non-zero divisor or guard the operation before evaluating it
DOUBLE_DELETE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = DOUBLE_DELETE
    .label = diagnostic
double-release = {$detail}
    .title = Value was released more than once
    .code = DOUBLE_RELEASE
    .label = already released
EVAL_START_PROMOTED = {$message}
    .title = Eval input promoted to a program
    .code = EVAL_START_PROMOTED
    .label = top-level Start declaration
EXECUTION_POLICY_DENIED = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = EXECUTION_POLICY_DENIED
    .label = diagnostic
FORMAT_OUT_OF_RANGE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = FORMAT_OUT_OF_RANGE
    .label = diagnostic
function-not-found = {$detail}
    .title = Function was not found at runtime
    .code = FUNCTION_NOT_FOUND
    .label = unknown function
HANDLER_NOT_FOUND = {$message}
    .title = Runtime or toolchain diagnostic
    .code = HANDLER_NOT_FOUND
    .label = diagnostic
HEADER_NOT_FOUND = {$message}
    .title = Runtime or toolchain diagnostic
    .code = HEADER_NOT_FOUND
    .label = diagnostic
HOST_CAPABILITY_UNAVAILABLE = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = HOST_CAPABILITY_UNAVAILABLE
    .label = diagnostic
INDEX_OUT_OF_BOUNDS = Index {$index} is outside {$context} (bound: {$bound}).
    .title = Index out of bounds
    .code = INDEX_OUT_OF_BOUNDS
    .label = invalid index
    .cause = the index is negative or greater than the available length
    .help = use an index in the range zero through bound minus one
INPUT_ERROR = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = INPUT_ERROR
    .label = diagnostic
INVALID_EGRESS_POLICY = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_EGRESS_POLICY
    .label = diagnostic
INVALID_DATE = {$detail}
    .title = Invalid date
    .code = INVALID_DATE
    .label = invalid date value
INVALID_EXIT_CODE = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_EXIT_CODE
    .label = diagnostic
INVALID_EXPONENT = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_EXPONENT
    .label = diagnostic
INVALID_FOR_STEP = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_FOR_STEP
    .label = diagnostic
INVALID_INPUT = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_INPUT
    .label = diagnostic
INVALID_JSON = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_JSON
    .label = diagnostic
INVALID_NUMERIC_CONVERSION = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_NUMERIC_CONVERSION
    .label = diagnostic
INVALID_OPTIONS = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_OPTIONS
    .label = diagnostic
INVALID_SHIFT_COUNT = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_SHIFT_COUNT
    .label = diagnostic
INVALID_START = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_START
    .label = diagnostic
INVALID_TIME = {$detail}
    .title = Invalid time
    .code = INVALID_TIME
    .label = invalid time value
INVALID_TIMEZONE = {$detail}
    .title = Invalid timezone
    .code = INVALID_TIMEZONE
    .label = invalid timezone value
INVALID_VALUE = {$detail}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_VALUE
    .label = diagnostic
IO = {$message}
    .title = Runtime or toolchain diagnostic
    .code = IO
    .label = diagnostic
LIMIT = {$message}
    .title = Runtime or toolchain diagnostic
    .code = LIMIT
    .label = diagnostic
NAME_NOT_FOUND = Name '{$name}' was not found in {$context}.
    .title = Undefined name
    .code = NAME_NOT_FOUND
    .label = unknown name
    .cause = the runtime lookup has no member or builtin with that name
    .help = verify the spelling and use the member or builtin exposed by the receiver
NOT_FOUND = {$message}
    .title = Runtime or toolchain diagnostic
    .code = NOT_FOUND
    .label = diagnostic
NULL_POINTER_ACCESS = {$message}
    .title = Runtime or toolchain diagnostic
    .code = NULL_POINTER_ACCESS
    .label = diagnostic
OUTPUT_ERROR = {$message}
    .title = Runtime or toolchain diagnostic
    .code = OUTPUT_ERROR
    .label = diagnostic
PARSE_ERROR = {$message}
    .title = Runtime value could not be parsed
    .code = PARSE_ERROR
    .label = invalid runtime value
POINTER_LENGTH_MISMATCH = {$message}
    .title = Runtime or toolchain diagnostic
    .code = POINTER_LENGTH_MISMATCH
    .label = diagnostic
PROCESS_LOG_WRITE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = PROCESS_LOG_WRITE
    .label = diagnostic
REQUEST_INVALID = {$message}
    .title = Runtime or toolchain diagnostic
    .code = REQUEST_INVALID
    .label = diagnostic
RETAIN_OVERFLOW = {$message}
    .title = Ownership count overflow
    .code = RETAIN_OVERFLOW
    .label = value has too many owners
RESOURCE_LIMIT = {$message}
    .title = Runtime or toolchain diagnostic
    .code = RESOURCE_LIMIT
    .label = diagnostic
SCRAPER_INPUT = {$message}
    .title = Runtime or toolchain diagnostic
    .code = SCRAPER_INPUT
    .label = diagnostic
SERVER_STATE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = SERVER_STATE
    .label = diagnostic
SESSION_CONFIG = {$message}
    .title = Runtime or toolchain diagnostic
    .code = SESSION_CONFIG
    .label = diagnostic
STALE_HANDLE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = STALE_HANDLE
    .label = diagnostic
START_NOT_FOUND = {$message}
    .title = Runtime or toolchain diagnostic
    .code = START_NOT_FOUND
    .label = diagnostic
STATIC_INITIALIZATION_CYCLE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = STATIC_INITIALIZATION_CYCLE
    .label = diagnostic
TLS_PROVIDER_UNAVAILABLE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = TLS_PROVIDER_UNAVAILABLE
    .label = diagnostic
UNINITIALIZED_VALUE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = UNINITIALIZED_VALUE
    .label = diagnostic
USE_AFTER_DELETE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = USE_AFTER_DELETE
    .label = diagnostic
use-after-release = {$detail}
    .title = Released value cannot be used
    .code = USE_AFTER_RELEASE
    .label = value was released
VECTOR_LENGTH_MISMATCH = {$message}
    .title = Runtime or toolchain diagnostic
    .code = VECTOR_LENGTH_MISMATCH
    .label = diagnostic
WEB_LISTEN = {$message}
    .title = Runtime or toolchain diagnostic
    .code = WEB_LISTEN
    .label = diagnostic
