# Runtime and IR diagnostics
invalid-ir = Invalid intermediate representation: {$detail}
    .title = Invalid intermediate representation
    .code = INVALID_IR
    .label = invalid IR
    .cause = the lowered program broke an IR rule that validation enforces
    .help = this is a toolchain defect: report it with the program that triggers it
ir-lowering = IR lowering failed: {$detail}
    .title = IR lowering failed
    .code = IR_LOWERING
    .label = unsupported lowering
    .cause = the program uses a construct the lowering to BN IR does not handle
    .help = this is a toolchain defect: report it with the program that triggers it
IMPORT_CYCLE = Import cycle includes {$detail}.
    .title = Import cycle
    .code = IMPORT_CYCLE
    .label = cycle edge
    .cause = the modules import each other in a loop, so none can be analyzed first
    .help = move the shared declarations into a module that both import
IMPORT_EXPORT_NOT_FOUND = Qualified import failed: {$detail}.
    .title = Imported export not found
    .code = IMPORT_EXPORT_NOT_FOUND
    .label = not an export of the module
    .cause = the qualified name is neither an EXPORT of the module nor a nested module
    .help = export the declaration from the module, or correct the qualified name
MODULE_LIMIT = Module graph limit exceeded: {$detail}.
    .title = Module graph limit exceeded
    .code = MODULE_LIMIT
    .label = module graph
    .cause = the import graph is larger or deeper than the toolchain's bound
    .help = reduce the number or nesting of imported modules
ALLOCATION_SIZE_INVALID = {$detail}
    .title = Invalid allocation length
    .code = ALLOCATION_SIZE_INVALID
    .label = allocation length
    .cause = the length given to NEW is negative or not an integer
    .help = give NEW a non-negative integer length
ALLOCATION_SIZE_OVERFLOW = {$detail}
    .title = Allocation size overflow
    .code = ALLOCATION_SIZE_OVERFLOW
    .label = allocation
    .cause = the length times the element size does not fit the host's address range
    .help = allocate fewer elements, or split the data across several regions
ALLOCATION_TOO_LARGE = {$detail}
    .title = Allocation too large
    .code = ALLOCATION_TOO_LARGE
    .label = allocation
    .cause = the host cannot reserve memory for a region this large, or its allocation table is full
    .help = allocate less, or RELEASE regions that are no longer needed
BUILD_EMISSION_FAILED = {$message}
    .title = Native code generation failed
    .code = BUILD_EMISSION_FAILED
    .label = build
    .cause = the LLVM toolchain rejected the code bnc generated for this program
    .help = this is a bnc defect: report it with the program; `bni run` executes the program meanwhile
BUILD_TOOLCHAIN_UNAVAILABLE = {$message}
    .title = Native toolchain unavailable
    .code = BUILD_TOOLCHAIN_UNAVAILABLE
    .label = build
    .cause = bnc could not run clang or find the bn_rt runtime library it links against
    .help = install LLVM 22 (clang), and set BN_RT_LIB or build bn_rt when working from a source checkout
CONFIG_INVALID = {$message}
    .title = Invalid configuration
    .code = CONFIG_INVALID
    .label = configuration
    .cause = a configuration file or option could not be read or holds a value outside its allowed range
    .help = correct the setting named in the message in config.toml or on the command line
DEBUG_TERMINATED = {$message}
    .title = Terminated by the debugger
    .code = DEBUG_TERMINATED
    .label = stopped here
    .cause = the debug adapter ended the program before it finished
    .help = run the program again, without stopping it from the debugger, to let it finish
DISPATCH = {$detail}
    .title = Dispatch failure
    .code = DISPATCH
    .label = dispatch
    .cause = a BNDispatch queue, ticket, barrier, or semaphore rejected the operation, or a worker failed
    .help = check the counts and timeouts passed to BNDispatch, and the Error the worker returned
DIVISION_BY_ZERO = {$operation} cannot use zero as its divisor.
    .title = Division by zero
    .code = DIVISION_BY_ZERO
    .label = zero divisor
    .cause = the right-hand operand evaluated to zero
    .help = provide a non-zero divisor or guard the operation before evaluating it
double-release = {$detail}
    .title = Value was released more than once
    .code = DOUBLE_RELEASE
    .label = already released
    .cause = RELEASE ran on a binding that an earlier RELEASE already ended
    .help = RELEASE each binding once; after RELEASE the binding is unusable
EVAL_START_PROMOTED = {$message}
    .title = Eval input promoted to a program
    .code = EVAL_START_PROMOTED
    .label = top-level Start declaration
    .cause = the eval input declares FUNCTION Start, so it runs as a whole program
    .help = remove Start to evaluate a snippet, or use `bni run` for programs
EXECUTION_POLICY_DENIED = {$detail}
    .title = Denied by execution policy
    .code = EXECUTION_POLICY_DENIED
    .label = denied
    .cause = the host's execution policy does not allow this operation or this path
    .help = grant the capability or the path in the execution policy, or use a path inside the allowed roots
FORMAT_OUT_OF_RANGE = {$message}
    .title = Date or time out of range
    .code = FORMAT_OUT_OF_RANGE
    .label = out of range
    .cause = the value lies outside the civil range 0001-01-01 through 9999-12-31
    .help = keep DATE and TIMESTAMP values within the years 0001 to 9999
function-not-found = {$detail}
    .title = Function was not found at runtime
    .code = FUNCTION_NOT_FOUND
    .label = unknown function
    .cause = no function with that name exists in the running program or its modules
    .help = check the name and the IMPORT that should provide it
HANDLER_NOT_FOUND = {$message}
    .title = Route handler unavailable
    .code = HANDLER_NOT_FOUND
    .label = route handler
    .cause = the BNWeb route refers to a handler that is no longer live
    .help = keep the handler registered for as long as the server routes requests to it
HEADER_NOT_FOUND = {$message}
    .title = HTTP header not present
    .code = HEADER_NOT_FOUND
    .label = header
    .cause = the response has no header with that name
    .help = set the header before reading it, or check that it is present first
HOST_CAPABILITY_UNAVAILABLE = {$detail}
    .title = Host capability unavailable
    .code = HOST_CAPABILITY_UNAVAILABLE
    .label = host capability
    .cause = the host running the program does not provide this HOST capability or function
    .help = run the program on a host that provides the capability, or remove the call
LIBRARY_PROVIDER_UNAVAILABLE = {$detail}
    .title = Library provider unavailable
    .code = LIBRARY_PROVIDER_UNAVAILABLE
    .label = this build of bn does not provide the library
    .cause = this build of the toolchain was compiled without that library's provider
    .help = use a build that includes the library (the default features), or remove the IMPORT
INDEX_OUT_OF_BOUNDS = Index {$index} is outside {$context} (bound: {$bound}).
    .title = Index out of bounds
    .code = INDEX_OUT_OF_BOUNDS
    .label = invalid index
    .cause = the index is negative or greater than the available length
    .help = use an index in the range zero through bound minus one
INPUT_ERROR = {$detail}
    .title = Cannot read input
    .code = INPUT_ERROR
    .label = input
    .cause = reading standard input failed in the operating system
    .help = check that standard input is open and readable (a closed pipe or terminal ends it)
INVALID_EGRESS_POLICY = {$detail}
    .title = Invalid egress policy
    .code = INVALID_EGRESS_POLICY
    .label = egress policy
    .cause = a BNWeb.EgressPolicy setting is outside its allowed range
    .help = use a positive deadline and a redirect limit within the documented bounds
INVALID_DATE = {$detail}
    .title = Invalid date
    .code = INVALID_DATE
    .label = invalid date value
    .cause = the text or components do not form a calendar date in 0001-01-01..9999-12-31
    .help = use ISO 8601 YYYY-MM-DD with a valid month and day
INVALID_EXIT_CODE = {$detail}
    .title = Exit code out of range
    .code = INVALID_EXIT_CODE
    .label = exit code
    .cause = a process exit code must be within 0..255
    .help = RETURN from Start, or STOP, with a value from 0 to 255
INVALID_EXPONENT = {$detail}
    .title = Invalid integer exponent
    .code = INVALID_EXPONENT
    .label = exponent
    .cause = an integer power needs a non-negative exponent small enough for the result type
    .help = use a non-negative exponent, or convert the operands to FLOAT for fractional or very large powers
INVALID_FOR_STEP = {$message}
    .title = FOR STEP is zero
    .code = INVALID_FOR_STEP
    .label = STEP
    .cause = a FOR loop whose STEP is 0 never reaches its end value
    .help = use a positive STEP to count up or a negative STEP to count down
INVALID_INPUT = {$detail}
    .title = Invalid network value
    .code = INVALID_INPUT
    .label = network value
    .cause = a HOST.Net value passed to the operation is malformed or out of range
    .help = build addresses with Net.Address.Parse and use ports within 0..65535
INVALID_NUMERIC_CONVERSION = {$message}
    .title = Invalid numeric conversion
    .code = INVALID_NUMERIC_CONVERSION
    .label = conversion
    .cause = NAN and infinity have no integer value
    .help = test the FLOAT value before converting it to an integer type
INVALID_OPTIONS = {$message}
    .title = Invalid server options
    .code = INVALID_OPTIONS
    .label = server options
    .cause = a BNWeb.ServerOptions field has the wrong type or a negative value
    .help = set each option to its documented type and a non-negative value
INVALID_SHIFT_COUNT = {$detail}
    .title = Invalid shift count
    .code = INVALID_SHIFT_COUNT
    .label = shift count
    .cause = the shift count is negative or not smaller than the width of the shifted operand in bits
    .help = shift by 0 up to the operand's width minus one
INVALID_START = {$detail}
    .title = Invalid FUNCTION Start
    .code = INVALID_START
    .label = Start
    .cause = FUNCTION Start takes no parameters and returns VOID or INTEGER
    .help = declare it as FUNCTION Start() AS INTEGER or FUNCTION Start() AS VOID
INVALID_TIME = {$detail}
    .title = Invalid time
    .code = INVALID_TIME
    .label = invalid time value
    .cause = the text or components do not form a time of day
    .help = use HH:MM:SS.mmm within 00:00:00.000..23:59:59.999
INVALID_TIMEZONE = {$detail}
    .title = Invalid timezone
    .code = INVALID_TIMEZONE
    .label = invalid timezone value
    .cause = the text is not a timezone the host knows
    .help = use a UTC offset (+03:00) or a timezone name the host's database provides
INVALID_VALUE = {$detail}
    .title = Invalid host value
    .code = INVALID_VALUE
    .label = value
    .cause = the value is not a valid instance of the HOST type the operation expects
    .help = create the value with its constructor or Parse function
IO = {$message}
    .title = Input/output failure
    .code = IO
    .label = I/O
    .cause = the operating system reported a failure while writing or reading
    .help = check the stream or resource the message names (a closed pipe, a full disk)
LIMIT = {$message}
    .title = Byte count exceeds the buffer
    .code = LIMIT
    .label = byte count
    .cause = the byte count is larger than the buffer, or than the operation's per-call bound
    .help = pass a count no larger than LEN(buffer) and within the operation's bound
NAME_NOT_FOUND = Name '{$name}' was not found in {$context}.
    .title = Undefined name
    .code = NAME_NOT_FOUND
    .label = unknown name
    .cause = the runtime lookup has no member or builtin with that name
    .help = verify the spelling and use the member or builtin exposed by the receiver
NOT_FOUND = {$message}
    .title = Key not found
    .code = NOT_FOUND
    .label = key
    .cause = the requested key or member does not exist
    .help = check that the key exists before reading it
NULL_POINTER_ACCESS = {$message}
    .title = NULL pointer access
    .code = NULL_POINTER_ACCESS
    .label = NULL pointer
    .cause = the pointer holds no region (NULL)
    .help = allocate the region with NEW, or compare the pointer with NULL before using it
OUTPUT_ERROR = {$message}
    .title = Cannot write output
    .code = OUTPUT_ERROR
    .label = output
    .cause = writing standard output failed in the operating system
    .help = check where standard output goes (a closed pipe or a full disk stops it)
PARSE_ERROR = {$message}
    .title = Runtime value could not be parsed
    .code = PARSE_ERROR
    .label = invalid runtime value
    .cause = the text does not have the form the Parse operation requires
    .help = check the text against the operation's documented format, or use TryParse to get an Error value
POINTER_LENGTH_MISMATCH = {$message}
    .title = Pointer length mismatch
    .code = POINTER_LENGTH_MISMATCH
    .label = pointer length
    .cause = the region's length differs from the length the target type declares
    .help = allocate the region with the declared length, or declare the pointer without a fixed length
PROCESS_LOG_WRITE = {$message}
    .title = Cannot write the process log
    .code = PROCESS_LOG_WRITE
    .label = process log
    .cause = the process log file could not be created or written
    .help = check the log path given to --log or in config.toml, and its directory's permissions
REQUEST_INVALID = {$message}
    .title = Invalid HTTP request
    .code = REQUEST_INVALID
    .label = request
    .cause = the request is malformed or exceeds a BNWeb limit
    .help = send a well-formed request within the server's limits
RETAIN_OVERFLOW = {$message}
    .title = Ownership count overflow
    .code = RETAIN_OVERFLOW
    .label = value has too many owners
    .cause = the value's strong reference count reached its maximum
    .help = hold fewer simultaneous strong references to the value
RESOURCE_LIMIT = {$message}
    .title = Resource limit exceeded
    .code = RESOURCE_LIMIT
    .label = input size
    .cause = the input is larger than the bound the operation accepts
    .help = split the input into smaller parts
SCRAPER_INPUT = {$message}
    .title = Invalid scraper input
    .code = SCRAPER_INPUT
    .label = HTML
    .cause = the text given to the BNWeb scraper cannot be parsed or exceeds its bound
    .help = pass complete HTML within the scraper's size bound
SERVER_STATE = {$message}
    .title = Server state unavailable
    .code = SERVER_STATE
    .label = server
    .cause = the BNWeb server was stopped, or its state is no longer available
    .help = use the server only between Start and Stop
SESSION_CONFIG = {$message}
    .title = Invalid session configuration
    .code = SESSION_CONFIG
    .label = session store
    .cause = a BNWeb.SessionStore setting is outside its allowed values
    .help = use the documented types and bounds for the session store
STALE_HANDLE = {$message}
    .title = Stale handle
    .code = STALE_HANDLE
    .label = handle
    .cause = the handle refers to an object that was closed, released, or never created
    .help = keep the object alive while using it, and do not use it after Close or RELEASE
START_NOT_FOUND = {$message}
    .title = FUNCTION Start not found
    .code = START_NOT_FOUND
    .label = module
    .cause = an executable module must declare FUNCTION Start
    .help = add FUNCTION Start() AS INTEGER, or import this file as a module instead of running it
STATIC_INITIALIZATION_CYCLE = {$message}
    .title = STATIC initialization cycle
    .code = STATIC_INITIALIZATION_CYCLE
    .label = STATIC member
    .cause = initializing a class's STATIC members needed those same STATIC members
    .help = break the cycle so that no STATIC initializer depends, directly or not, on its own class
TLS_PROVIDER_UNAVAILABLE = {$message}
    .title = TLS unavailable
    .code = TLS_PROVIDER_UNAVAILABLE
    .label = TLS
    .cause = the host provides no TLS implementation for this BNWeb operation
    .help = use a build with TLS support, or serve plain HTTP behind a TLS proxy
UNINITIALIZED_VALUE = {$message}
    .title = Value read before assignment
    .code = UNINITIALIZED_VALUE
    .label = unassigned
    .cause = the binding or vector element has not been given a value on this path
    .help = assign a value on every path before reading it
use-after-release = {$detail}
    .title = Released value cannot be used
    .code = USE_AFTER_RELEASE
    .label = value was released
    .cause = the binding was used after RELEASE ended it
    .help = do not use a binding after RELEASE; keep another binding if the value is still needed
VECTOR_LENGTH_MISMATCH = {$message}
    .title = Vector length mismatch
    .code = VECTOR_LENGTH_MISMATCH
    .label = vector length
    .cause = the assigned vector's length differs from the declared length
    .help = assign a vector of the declared length
WEB_LISTEN = {$message}
    .title = Cannot start the HTTP server
    .code = WEB_LISTEN
    .label = listen
    .cause = the server could not listen on the endpoint: it is in use, not permitted, or TLS setup failed
    .help = choose a free port you may bind, and check the TLS certificate and key
