# Runtime and IR diagnostics
invalid-ir = {$message}
    .title = Invalid intermediate representation
    .code = INVALID_IR
    .label = invalid IR
ir-lowering = {$message}
    .title = IR lowering failed
    .code = IR_LOWERING
    .label = unsupported lowering
ALLOCATION_SIZE_INVALID = {$message}
    .title = Runtime or toolchain diagnostic
    .code = ALLOCATION_SIZE_INVALID
    .label = diagnostic
ALLOCATION_SIZE_OVERFLOW = {$message}
    .title = Runtime or toolchain diagnostic
    .code = ALLOCATION_SIZE_OVERFLOW
    .label = diagnostic
ALLOCATION_TOO_LARGE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = ALLOCATION_TOO_LARGE
    .label = diagnostic
BUILD_EMISSION_FAILED = {$message}
    .title = Runtime or toolchain diagnostic
    .code = BUILD_EMISSION_FAILED
    .label = diagnostic
BUILD_TOOLCHAIN_UNAVAILABLE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = BUILD_TOOLCHAIN_UNAVAILABLE
    .label = diagnostic
CONFIG_INVALID = {$message}
    .title = Runtime or toolchain diagnostic
    .code = CONFIG_INVALID
    .label = diagnostic
DEBUG_TERMINATED = {$message}
    .title = Runtime or toolchain diagnostic
    .code = DEBUG_TERMINATED
    .label = diagnostic
DISPATCH = {$message}
    .title = Runtime or toolchain diagnostic
    .code = DISPATCH
    .label = diagnostic
DIVISION_BY_ZERO = {$message}
    .title = Runtime or toolchain diagnostic
    .code = DIVISION_BY_ZERO
    .label = diagnostic
DOUBLE_DELETE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = DOUBLE_DELETE
    .label = diagnostic
EXECUTION_POLICY_DENIED = {$message}
    .title = Runtime or toolchain diagnostic
    .code = EXECUTION_POLICY_DENIED
    .label = diagnostic
FORMAT_OUT_OF_RANGE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = FORMAT_OUT_OF_RANGE
    .label = diagnostic
HANDLER_NOT_FOUND = {$message}
    .title = Runtime or toolchain diagnostic
    .code = HANDLER_NOT_FOUND
    .label = diagnostic
HEADER_NOT_FOUND = {$message}
    .title = Runtime or toolchain diagnostic
    .code = HEADER_NOT_FOUND
    .label = diagnostic
HOST_CAPABILITY_UNAVAILABLE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = HOST_CAPABILITY_UNAVAILABLE
    .label = diagnostic
INDEX_OUT_OF_BOUNDS = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INDEX_OUT_OF_BOUNDS
    .label = diagnostic
INPUT_ERROR = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INPUT_ERROR
    .label = diagnostic
INVALID_EGRESS_POLICY = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_EGRESS_POLICY
    .label = diagnostic
INVALID_EXIT_CODE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_EXIT_CODE
    .label = diagnostic
INVALID_EXPONENT = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_EXPONENT
    .label = diagnostic
INVALID_FOR_STEP = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_FOR_STEP
    .label = diagnostic
INVALID_INPUT = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_INPUT
    .label = diagnostic
INVALID_JSON = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_JSON
    .label = diagnostic
INVALID_NUMERIC_CONVERSION = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_NUMERIC_CONVERSION
    .label = diagnostic
INVALID_OPTIONS = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_OPTIONS
    .label = diagnostic
INVALID_SHIFT_COUNT = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_SHIFT_COUNT
    .label = diagnostic
INVALID_START = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_START
    .label = diagnostic
INVALID_VALUE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = INVALID_VALUE
    .label = diagnostic
IO = {$message}
    .title = Runtime or toolchain diagnostic
    .code = IO
    .label = diagnostic
LIMIT = {$message}
    .title = Runtime or toolchain diagnostic
    .code = LIMIT
    .label = diagnostic
NAME_NOT_FOUND = {$message}
    .title = Runtime or toolchain diagnostic
    .code = NAME_NOT_FOUND
    .label = diagnostic
NOT_FOUND = {$message}
    .title = Runtime or toolchain diagnostic
    .code = NOT_FOUND
    .label = diagnostic
NULL_POINTER_ACCESS = {$message}
    .title = Runtime or toolchain diagnostic
    .code = NULL_POINTER_ACCESS
    .label = diagnostic
OUTPUT_ERROR = {$message}
    .title = Runtime or toolchain diagnostic
    .code = OUTPUT_ERROR
    .label = diagnostic
POINTER_LENGTH_MISMATCH = {$message}
    .title = Runtime or toolchain diagnostic
    .code = POINTER_LENGTH_MISMATCH
    .label = diagnostic
PROCESS_LOG_WRITE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = PROCESS_LOG_WRITE
    .label = diagnostic
REQUEST_INVALID = {$message}
    .title = Runtime or toolchain diagnostic
    .code = REQUEST_INVALID
    .label = diagnostic
RESOURCE_LIMIT = {$message}
    .title = Runtime or toolchain diagnostic
    .code = RESOURCE_LIMIT
    .label = diagnostic
SCRAPER_INPUT = {$message}
    .title = Runtime or toolchain diagnostic
    .code = SCRAPER_INPUT
    .label = diagnostic
SERVER_STATE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = SERVER_STATE
    .label = diagnostic
SESSION_CONFIG = {$message}
    .title = Runtime or toolchain diagnostic
    .code = SESSION_CONFIG
    .label = diagnostic
STALE_HANDLE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = STALE_HANDLE
    .label = diagnostic
START_NOT_FOUND = {$message}
    .title = Runtime or toolchain diagnostic
    .code = START_NOT_FOUND
    .label = diagnostic
STATIC_INITIALIZATION_CYCLE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = STATIC_INITIALIZATION_CYCLE
    .label = diagnostic
TLS_PROVIDER_UNAVAILABLE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = TLS_PROVIDER_UNAVAILABLE
    .label = diagnostic
UNINITIALIZED_VALUE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = UNINITIALIZED_VALUE
    .label = diagnostic
USE_AFTER_DELETE = {$message}
    .title = Runtime or toolchain diagnostic
    .code = USE_AFTER_DELETE
    .label = diagnostic
VECTOR_LENGTH_MISMATCH = {$message}
    .title = Runtime or toolchain diagnostic
    .code = VECTOR_LENGTH_MISMATCH
    .label = diagnostic
WEB_LISTEN = {$message}
    .title = Runtime or toolchain diagnostic
    .code = WEB_LISTEN
    .label = diagnostic
