# Semantic diagnostics
type-mismatch = Expected {$expected}, but found {$actual} in {$context}.
    .title = Type mismatch
    .code = TYPE_MISMATCH
    .label = incompatible value
    .cause = the value does not satisfy the operation's type contract
    .help = convert the value or change the receiving declaration to the expected type
numeric-overflow = Numeric overflow while {$operation}.
    .title = Numeric overflow
    .code = NUMERIC_OVERFLOW
    .label = overflow
    .help = use a wider numeric type or reduce the value
unused-binding = Binding '{$name}' is never read.
    .title = Unused binding
    .code = UNUSED_BINDING
    .label = never read
    .help = remove the binding or use it
unused-import = Imported module '{$module}' is never used.
    .title = Unused import
    .code = UNUSED_IMPORT
    .label = never used
    .help = remove the import
unreachable-code = This code is unreachable ({$context}).
    .title = Unreachable code
    .code = UNREACHABLE_CODE
    .label = unreachable
ASYNC_RETURN_TYPE = {$message}
    .title = Invalid async return type
    .code = ASYNC_RETURN_TYPE
ASYNC_TARGET = {$message}
    .title = Invalid async target
    .code = ASYNC_TARGET
AWAIT_TIMEOUT = {$message}
    .title = Invalid await timeout
    .code = AWAIT_TIMEOUT
DUPLICATE_INTERFACE = {$message}
    .title = Duplicate interface
    .code = DUPLICATE_INTERFACE
DUPLICATE_NAME = Declaration '{$name}' duplicates an existing name.
    .title = Duplicate declaration
    .code = DUPLICATE_NAME
    .label = duplicate name
HOST_ARGS_SCOPE = {$message}
    .title = HOST.Args is out of scope
    .code = HOST_ARGS_SCOPE
HOST_IMPORT_SCOPE = {$message}
    .title = HOST import is out of scope
    .code = HOST_IMPORT_SCOPE
IMPORTED_START = {$message}
    .title = Imported module declares Start
    .code = IMPORTED_START
INHERITANCE_CYCLE = {$message}
    .title = Inheritance cycle
    .code = INHERITANCE_CYCLE
INPUT_PROMPT_TYPE = {$message}
    .title = Invalid input prompt type
    .code = INPUT_PROMPT_TYPE
INVALID_ALTERNATIVE_USE = {$message}
    .title = Invalid alternative use
    .code = INVALID_ALTERNATIVE_USE
INVALID_CONSTRUCTOR = {$message}
    .title = Invalid constructor
    .code = INVALID_CONSTRUCTOR
INVALID_DESTRUCTOR = {$message}
    .title = Invalid destructor
    .code = INVALID_DESTRUCTOR
INVALID_FILE_MODE = {$message}
    .title = Invalid file mode
    .code = INVALID_FILE_MODE
INVALID_HOST_ARGS_USE = {$message}
    .title = Invalid HOST.Args use
    .code = INVALID_HOST_ARGS_USE
INVALID_LOOP_CONTROL = {$message}
    .title = Invalid loop control
    .code = INVALID_LOOP_CONTROL
INVALID_OVERRIDE = {$message}
    .title = Invalid override
    .code = INVALID_OVERRIDE
INVALID_POINTER_TYPE = {$message}
    .title = Invalid pointer type
    .code = INVALID_POINTER_TYPE
INVALID_RELEASE_TARGET = {$message}
    .title = Invalid release target
    .code = INVALID_RELEASE_TARGET
INVALID_SUPER = {$message}
    .title = Invalid SUPER use
    .code = INVALID_SUPER
INVALID_VECTOR_DIMENSION = {$message}
    .title = Invalid vector dimension
    .code = INVALID_VECTOR_DIMENSION
INVALID_VECTOR_TYPE = {$message}
    .title = Invalid vector type
    .code = INVALID_VECTOR_TYPE
MISSING_RETURN = {$message}
    .title = Missing return
    .code = MISSING_RETURN
MODULE_NOT_RESOLVED = {$message}
    .title = Module was not resolved
    .code = MODULE_NOT_RESOLVED
NOT_CALLABLE = {$message}
    .title = Value is not callable
    .code = NOT_CALLABLE
PRIVATE_ACCESS = {$message}
    .title = Private member access
    .code = PRIVATE_ACCESS
PROTECTED_ACCESS = {$message}
    .title = Protected member access
    .code = PROTECTED_ACCESS
TYPE_NAME_AS_VALUE = {$message}
    .title = Type name used as a value
    .code = TYPE_NAME_AS_VALUE
UNKNOWN_TYPE = {$message}
    .title = Unknown type
    .code = UNKNOWN_TYPE
UNRESOLVED_TYPE = {$message}
    .title = Unresolved type
    .code = UNRESOLVED_TYPE
