# Semantic diagnostics
type-mismatch = Expected {$expected}, but found {$actual} in {$context}.
    .title = Type mismatch
    .code = TYPE_MISMATCH
    .label = incompatible value
    .cause = the value does not satisfy the operation's type contract
    .help = convert the value or change the receiving declaration to the expected type
numeric-overflow = Numeric overflow while {$operation}.
    .title = Numeric overflow
    .code = NUMERIC_OVERFLOW
    .label = overflow
    .help = use a wider numeric type or reduce the value
    .cause = the exact result lies outside the range of the destination type
unused-binding = Binding '{$name}' is never read.
    .title = Unused binding
    .code = UNUSED_BINDING
    .label = never read
    .help = remove the binding or use it
    .cause = nothing reads the binding after it is assigned
unused-import = Imported module '{$module}' is never used.
    .title = Unused import
    .code = UNUSED_IMPORT
    .label = never used
    .help = remove the import
    .cause = no name, type, or capability from the imported module is used
unreachable-code = This code is unreachable ({$context}).
    .title = Unreachable code
    .code = UNREACHABLE_CODE
    .label = unreachable
    .cause = an earlier RETURN, EXIT, CONTINUE, or STOP always leaves this block first
    .help = remove the code, or move it before the statement that leaves the block
ASYNC_RETURN_TYPE = {$message}
    .title = Invalid async return type
    .code = ASYNC_RETURN_TYPE
    .cause = an ASYNC FUNCTION with a result reports failure as a value, so its type must admit Error
    .help = declare the result as T OR Error
ASYNC_TARGET = {$message}
    .title = Invalid async target
    .code = ASYNC_TARGET
    .cause = ASYNC submits a call by name; an expression cannot be dispatched
    .help = call a named FUNCTION: ASYNC queue Name(arguments)
AWAIT_TIMEOUT = {$message}
    .title = Invalid await timeout
    .code = AWAIT_TIMEOUT
    .cause = AWAIT waits a bounded time, from 1 to 60000 milliseconds
    .help = pass a timeout between 1 and 60000
DUPLICATE_INTERFACE = {$message}
    .title = Duplicate interface
    .code = DUPLICATE_INTERFACE
    .cause = a CLASS lists the same interface more than once in IMPLEMENTS
    .help = name each interface once
DUPLICATE_NAME = Declaration '{$name}' duplicates an existing name.
    .title = Duplicate declaration
    .code = DUPLICATE_NAME
    .label = duplicate name
    .cause = two declarations in the same scope use this name
    .help = rename one of the declarations
HOST_ARGS_SCOPE = {$message}
    .title = HOST.Args is out of scope
    .code = HOST_ARGS_SCOPE
    .cause = program arguments belong to the executable module, not to imported modules
    .help = read HOST.Args in the module that declares Start and pass the values on
HOST_IMPORT_SCOPE = {$message}
    .title = HOST import is out of scope
    .code = HOST_IMPORT_SCOPE
    .cause = this HOST capability is available only to the executable module
    .help = import it in the module that declares Start and pass what the module needs
IMPORTED_START = {$message}
    .title = Imported module declares Start
    .code = IMPORTED_START
    .cause = a module has one entry point, FUNCTION Start, in the executable module
    .help = remove Start from the imported module
INHERITANCE_CYCLE = {$message}
    .title = Inheritance cycle
    .code = INHERITANCE_CYCLE
    .cause = a class cannot extend itself, directly or through its ancestors
    .help = break the cycle in the EXTENDS chain
INPUT_PROMPT_TYPE = {$message}
    .title = Invalid input prompt type
    .code = INPUT_PROMPT_TYPE
    .cause = INPUT prints its prompt as text
    .help = pass a STRING prompt, or convert the value with AS STRING
INVALID_ALTERNATIVE_USE = {$message}
    .title = Invalid alternative use
    .code = INVALID_ALTERNATIVE_USE
    .cause = IS tests one alternative of the value's declared type
    .help = test a type the value can hold (x IS INTEGER for an INTEGER OR Error), or NULL, NA, EOF, NAN, INF
INVALID_CONSTRUCTOR = {$message}
    .title = Invalid constructor
    .code = INVALID_CONSTRUCTOR
    .cause = the arguments or the declaration do not match the class's CONSTRUCTOR
    .help = pass the arguments the CONSTRUCTOR declares, and declare it as an instance FUNCTION
INVALID_DESTRUCTOR = {$message}
    .title = Invalid destructor
    .code = INVALID_DESTRUCTOR
    .cause = a DESTRUCTOR runs without arguments when the last reference goes away
    .help = declare DESTRUCTOR as an instance FUNCTION with no parameters
INVALID_FILE_MODE = {$message}
    .title = Invalid file mode
    .code = INVALID_FILE_MODE
    .cause = FS.Open accepts the mode constants FS.READ, FS.WRITE, and FS.APPEND
    .help = pass one of FS.READ, FS.WRITE, or FS.APPEND
INVALID_HOST_ARGS_USE = {$message}
    .title = Invalid HOST.Args use
    .code = INVALID_HOST_ARGS_USE
    .cause = HOST.Args is not a value; only its length and elements can be read
    .help = use LEN(HOST.Args) or HOST.Args[index]
INVALID_LOOP_CONTROL = {$message}
    .title = Invalid loop control
    .code = INVALID_LOOP_CONTROL
    .cause = EXIT and CONTINUE name the loop they leave, and that loop must enclose them
    .help = place the statement inside the named loop, or name the loop that encloses it
INVALID_OVERRIDE = {$message}
    .title = Invalid override
    .code = INVALID_OVERRIDE
    .cause = the member cannot override: STATIC methods are not virtual, and inherited members keep their kind
    .help = remove OVERRIDE from a STATIC method, or give the member another name
OVERRIDE_REQUIRED = {$message}
    .title = OVERRIDE marker required
    .code = OVERRIDE_REQUIRED
    .cause = replacing an inherited method must be explicit
    .help = mark the method OVERRIDE: PUBLIC OVERRIDE FUNCTION Name
OVERRIDE_WITHOUT_BASE = {$message}
    .title = OVERRIDE without a base method
    .code = OVERRIDE_WITHOUT_BASE
    .cause = OVERRIDE replaces a method of an ancestor, and there is none with this name
    .help = remove OVERRIDE, or EXTEND the class that declares the method
INVALID_POINTER_TYPE = {$message}
    .title = Invalid pointer type
    .code = INVALID_POINTER_TYPE
    .cause = a POINTER names a numeric or declared element type
    .help = write POINTER TO INTEGER[] or POINTER TO Name, optionally with a literal length
INVALID_RELEASE_TARGET = {$message}
    .title = Invalid release target
    .code = INVALID_RELEASE_TARGET
    .cause = RELEASE ends one binding of a pointer or CLASS reference
    .help = RELEASE a local binding that holds a pointer or an object
INVALID_SUPER = {$message}
    .title = Invalid SUPER use
    .code = INVALID_SUPER
    .cause = SUPER reaches the base class from a derived CLASS, and a derived constructor calls SUPER(...) first
    .help = call SUPER(...) as the first statement of the constructor, or SUPER.Name(...) for a base method
INVALID_VECTOR_DIMENSION = {$message}
    .title = Invalid vector dimension
    .code = INVALID_VECTOR_DIMENSION
    .cause = a vector's length is fixed by a non-negative integer
    .help = declare the vector with a non-negative integer length
INVALID_VECTOR_TYPE = {$message}
    .title = Invalid vector type
    .code = INVALID_VECTOR_TYPE
    .cause = variable-length vectors are reserved for the BNData library
    .help = declare a fixed length, or use a POINTER TO T[] region for a size known at run time
MISSING_RETURN = {$message}
    .title = Missing return
    .code = MISSING_RETURN
    .cause = some path through the FUNCTION reaches its end without RETURN
    .help = return a value on every path, or declare the FUNCTION AS VOID
MODULE_NOT_RESOLVED = {$message}
    .title = Module was not resolved
    .code = MODULE_NOT_RESOLVED
    .cause = the import graph did not resolve the module behind this alias
    .help = this is a toolchain defect when the IMPORT itself was accepted; report it with the program
NOT_CALLABLE = {$message}
    .title = Value is not callable
    .code = NOT_CALLABLE
    .cause = only functions and methods can be called
    .help = call a FUNCTION or method, or remove the parentheses
PRIVATE_ACCESS = {$message}
    .title = Private member access
    .code = PRIVATE_ACCESS
    .cause = PRIVATE members are reachable only inside the declaring class
    .help = use a PUBLIC member, or make the member PUBLIC
PROTECTED_ACCESS = {$message}
    .title = Protected member access
    .code = PROTECTED_ACCESS
    .cause = PROTECTED members are reachable only in the declaring class and in classes that EXTEND it
    .help = access the member from such a class, or make it PUBLIC
TYPE_NAME_AS_VALUE = {$message}
    .title = Type name used as a value
    .code = TYPE_NAME_AS_VALUE
    .cause = a type name denotes a type, not a value, except to the right of IS
    .help = create a value (NEW Name(...)) or use the type in a declaration or an IS test
UNKNOWN_TYPE = {$message}
    .title = Unknown type
    .code = UNKNOWN_TYPE
    .cause = no declaration or IMPORT in scope provides this type
    .help = declare the type, or IMPORT the module that exports it
UNRESOLVED_TYPE = {$message}
    .title = Unresolved type
    .code = UNRESOLVED_TYPE
    .cause = semantic analysis could not assign a type to the expression
    .help = this is a toolchain defect when no other error precedes it; report it with the program
bnsqlite-requires-bndata = {$detail}
    .title = BNSqlite requires BNData
    .code = E0450
    .label = missing companion import
    .cause = BNSqlite query results produce Data.DataFrame instances, requiring BNData
    .help = add 'IMPORT BNData AS Data' to the module imports
