[package]
name = "bnc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Basic Next compiler: bnc [compile-options] <entry.bn>"
license.workspace = true
publish = false

[[bin]]
name = "bnc"
path = "src/main.rs"

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"

[dependencies]
bn_cli = { path = "../bn_cli" }
bn_compile_driver = { path = "../bn_compile_driver" }
