[package]
name = "bn_value"
version.workspace = true
edition.workspace = true
rust-version = "1.97"
description = "Basic Next runtime value representation"
license.workspace = true
publish = false

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"

[dependencies]
bn_types = { path = "../bn_types" }

[dev-dependencies]
bn_source = { path = "../bn_source" }
